-- Maintenance alerts feature (docs/ALERTS_SPEC.md).
-- ddl-auto=update creates these automatically on boot; this file is the record
-- for a controlled / prod apply. Postgres dialect.

CREATE TABLE IF NOT EXISTS alert_preferences (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL UNIQUE REFERENCES users(id),
    alerts_enabled       BOOLEAN NOT NULL DEFAULT FALSE,
    check_hour           INTEGER NOT NULL DEFAULT 7,
    lead_time_days       INTEGER NOT NULL DEFAULT 30,
    lead_time_hours      INTEGER NOT NULL DEFAULT 10,
    overdue_renudge_days INTEGER NOT NULL DEFAULT 7,
    last_checked_on      DATE,
    baseline_sent_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS alert_recipients (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id),
    channel          VARCHAR(8) NOT NULL,
    destination      VARCHAR(255) NOT NULL,
    label            VARCHAR(255),
    status           VARCHAR(16) NOT NULL,
    confirm_token    VARCHAR(64) NOT NULL UNIQUE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_at     TIMESTAMP WITH TIME ZONE,
    reminder_sent_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS alert_send_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    channel      VARCHAR(8) NOT NULL,
    sent_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alert_send_recipient_sentat
    ON alert_send_log (recipient_id, sent_at);

ALTER TABLE service_timelines ADD COLUMN IF NOT EXISTS alert_level VARCHAR(255);
ALTER TABLE service_timelines ADD COLUMN IF NOT EXISTS alert_last_fired_at TIMESTAMP WITH TIME ZONE;
